### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by sandy0201** [szchenghuang/react-google-invisible-recaptcha#22]
Hi,

Recently I saw in the console that there is a 404 not found error:
`GET https://www.google.com/recaptcha/api2/undefined 404 (Not Found) undefined:1`

Not sure what the issue could be.

Could you please assist?

Thank you.
Kind regards.

**Comment by szchenghuang** [comment]
Hi, there! It's likely an issue of the reCatpcha service. Check this [SO](https://stackoverflow.com/questions/21297235/recaptcha-404s-errors) thread. HTH.

**Comment by szchenghuang** [comment]
Hi @sandy0201, I know as much as you do, but the [demo](https://szchenghuang.github.io/react-google-invisible-recaptcha/) widget is not unfolding this error. Do you still suffer from it? How do you render the reCaptcha?

**Comment by sandy0201** [comment]
Hi @szchenghuang , yes I do still see the error. I just checked the demo you've linked now, it also has the same 404 Not Found error. Kind regards.

**Comment by sandy0201** [comment]
![image](https://user-images.githubusercontent.com/2969051/45630470-074c3e80-ba99-11e8-8bcb-4608ba909ce1.png)

**Comment by szchenghuang** [comment]
The only external direct endpoint to access by this package is `https://www.google.com/recaptcha/api.js?hl=en&onload=GoogleRecaptchaLoaded&render=explicit` and since then the handoff begins at there. Your screenshot shows some indirect endpoints on your end is not redirected correctly. The `undefined` segments within those failed URL should have been translated from some variables and they were not interpreted peacefully. I would check the network to see if any firewall or the similar become obstacles. Also a result of the Google [demo](https://www.google.com/recaptcha/api2/demo) would be a good reference.

**Comment by sandy0201** [comment]
Ok cool, will try it out connecting to different network... might be our network that is causing the error. Thanks :)

**Comment by szchenghuang** [comment]
Let's close this for now but feel free to reopen if there is improvement needed.
